// Exact UI copy for the public site (French only). Move into your i18n/constants layer.
// Typography (non-breaking spaces before : ; ! ? and inside « »), apostrophes and
// ellipses are applied by the content formatter, not stored here.

export const labels = {
    brand: { name: 'Randy Donny', tagline: "Je pense, donc j'essuie..." },
    nav: {
        aboutMe: 'A propos de ma pomme', // sic, exactly as briefed (correct French: « À propos »)
        backHome: "Revenir à la page d'accueil",
        subscribe: "S'abonner",
    },
    home: {
        heroDescription:
            "Je ne peux plus accéder à mon blog sur Hautetfort. Tant pis, voici le nouveau. Mieux, c'est un site web avec mon propre nom de domaine. Je suis aussi principalement sur Facebook, X et LinkedIn. Enfin, j'ai une chaîne YouTube.",
        heroLinks: [
            'Hautetfort',
            'Facebook',
            'X',
            'LinkedIn',
            'chaîne YouTube',
        ],
        latest: 'Dernières publications',
        allArticles: 'Tous les articles',
        seeMore: 'Voir plus',
    },
    search: {
        placeholder: 'Rechercher un article…',
        submit: 'Rechercher',
        resultsFor: (q: string) => `Résultats pour « ${q} »`,
        empty: 'Aucun article ne correspond à votre recherche.',
    },
    pagination: {
        previous: 'Précédent',
        next: 'Suivant',
        page: (n: number, total: number) => `Page ${n} sur ${total}`,
    },
    categories: [
        'Politique',
        'Économie',
        'Culture',
        'Société',
        'International',
        'Insolite',
    ],
    article: {
        readingTime: (min: number) => `${min} min de lecture`,
        byline: 'Par',
        listen: "Écouter l'article",
        photoCredit: 'Crédit photo :',
        copyLink: 'Copier le lien',
        linkCopied: 'Lien copié',
        previous: 'Article précédent',
        next: 'Article suivant',
        ctaText:
            'Ce texte vous a plu ? Recevez les prochains directement par email.',
        preview: "Aperçu — cet article n'est pas publié",
        callout: 'Encadré', // generated by CSS ::before, listed for reference
    },
    author: { latest: 'Derniers articles' },
    subscription: {
        title: 'Restez informé',
        description:
            'Recevez mes nouveaux articles directement dans votre boîte mail.',
        emailLabel: 'Adresse email',
        emailPlaceholder: 'vous@exemple.fr',
        consent:
            'En vous abonnant, vous acceptez de recevoir mes nouveaux articles par email. Désabonnement possible à tout moment. Voir la Politique de confidentialité.',
        success:
            "Merci ! Un email de confirmation vient de vous être envoyé. Cliquez sur le lien qu'il contient pour valider votre abonnement.",
        invalidEmail: 'Veuillez saisir une adresse email valide.',
        disposableEmail:
            'Les adresses email temporaires ne sont pas acceptées.',
    },
    confirmation: {
        confirmedTitle: 'Votre abonnement est confirmé',
        expiredTitle: 'Ce lien a expiré',
        unsubscribedTitle: 'Vous êtes désabonné',
        // Body copy and secondary actions below are proposals, adjust freely.
        confirmedText:
            'Merci ! Vous recevrez désormais mes nouveaux articles directement dans votre boîte mail.',
        expiredText:
            "Le lien de confirmation n'est plus valide. Pas de panique : il suffit de vous abonner à nouveau pour en recevoir un nouveau.",
        unsubscribedText:
            "C'est fait : vous ne recevrez plus ma newsletter. Vous pouvez vous réabonner à tout moment, si l'envie vous en reprend.",
        subscribeAgain: "S'abonner à nouveau",
        resubscribe: 'Me réabonner',
        readLatest: 'Lire les derniers articles',
    },
    notFound: {
        title: 'Page introuvable',
        text: "Je pense, donc j'essuie… et cette page-là, on dirait que quelqu'un l'a essuyée pour de bon. Essayez une recherche, ou retournez d'où vous venez.",
    },
    footer: {
        follow: 'Suivre',
        info: 'Informations',
        privacy: 'Politique de confidentialité',
        copyright: '© 2026 Randy Donny',
        credit: 'Site conçu et développé par [Nom du développeur]', // placeholder
    },
    share: {
        facebook: 'Facebook',
        x: 'X',
        linkedin: 'LinkedIn',
        youtube: 'YouTube',
    },
    cookies: {
        text: "Ce site utilise Google Analytics pour mesurer son audience. Aucune donnée n'est utilisée à des fins publicitaires. Vous pouvez accepter, refuser ou choisir.",
        accept: 'Accepter',
        refuse: 'Refuser',
        customize: 'Personnaliser',
    },
    newsletter: {
        readArticle: "Lire l'article",
        footer: 'Vous recevez cet email car vous êtes abonné à la newsletter de Randy Donny.',
        unsubscribe: 'Se désabonner',
    },
} as const;
